name: Get or Create Release
description: Creates a GitHub release or attaches assets to an existing one
inputs:
  assets:
    description: File glob expression(s) of assets to attach to the release
    required: false
  body:
    description: Text describing the contents of the release
    required: false
  github_token:
    description: GitHub personal access token
    required: true
    default: ${{ github.token }}
  prerelease:
    description: true to identify the release as a prerelease
    required: false
  previous_release_sha:
    description: Commit SHA of the previous release
    required: false
  publish:
    description: true to publish the release, false to leave as a draft
    required: true
    default: "true"
  release_name:
    description: Name of the release
    required: false
  tag_name:
    description: Tag from which to create the release
    required: true
  target_commitish:
    description: Specifies where the tag is created from
    required: true
    default: ${{ github.sha }}
outputs:
  release_id:
    description: The ID of the release
  upload_url:
    description: The URL for uploading assets to the release
runs:
  using: node16
  main: dist/index.js
branding:
  icon: tag
  color: blue
